#include <BWAPI/Runtime/RuntimeBackend.h>
#include <BWAPI/Runtime/RuntimeInstallation.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#if defined(_WIN32)
#include <stdlib.h>
#endif

using namespace BWAPI::Runtime;

namespace
{
  void setEnvValue(const char* name, const std::string& value)
  {
    if (value.empty())
      return;
#if defined(_WIN32)
    _putenv_s(name, value.c_str());
#else
    setenv(name, value.c_str(), 1);
#endif
  }

  std::string shellQuote(const std::string& value)
  {
    std::string quoted = "'";
    for (char ch : value)
    {
      if (ch == '\'')
        quoted += "'\\''";
      else
        quoted.push_back(ch);
    }
    quoted.push_back('\'');
    return quoted;
  }

  bool writeEnvFile(const RuntimeInstallation& installation, const std::string& path, std::string& error)
  {
    std::ofstream output(path);
    if (!output)
    {
      error = "unable to write env file: " + path;
      return false;
    }

    output << "# Generated by starcraft-runtime-legacy1161-setup.\n";
    output << "export STARCRAFT_API_BW1161_DIR=" << shellQuote(installation.installRoot) << '\n';
    output << "export STARCRAFT_API_BW1161_EXE=" << shellQuote(installation.executablePath) << '\n';
    output << "export STARCRAFT_API_PRODUCT=1161\n";
    if (!installation.compatibilityRuntimePath.empty())
      output << "export STARCRAFT_API_WINE=" << shellQuote(installation.compatibilityRuntimePath) << '\n';
    if (!installation.compatibilityPrefix.empty())
      output << "export STARCRAFT_API_WINEPREFIX=" << shellQuote(installation.compatibilityPrefix) << '\n';
    return true;
  }

  bool hostNeedsCompatibilityRuntime(Platform platform)
  {
    return platform == Platform::MacOS || platform == Platform::Linux;
  }

  bool launchable(const RuntimeInstallation& installation)
  {
    if (!installation.found)
      return false;
    if (!hostNeedsCompatibilityRuntime(installation.platform))
      return true;
    return !installation.compatibilityRuntimePath.empty();
  }

  void printInstallation(const RuntimeInstallation& installation)
  {
    std::cout << "legacy1161.setup.checked=true\n";
    std::cout << "install.found=" << (installation.found ? "true" : "false") << '\n';
    std::cout << "platform=" << toString(installation.platform) << '\n';
    std::cout << "product=" << toString(installation.product) << '\n';
    std::cout << "version=" << (installation.version.empty() ? "unknown" : installation.version) << '\n';
    if (!installation.installRoot.empty())
      std::cout << "install.root=" << installation.installRoot << '\n';
    if (!installation.executablePath.empty())
      std::cout << "install.executable=" << installation.executablePath << '\n';
    if (!installation.compatibilityRuntime.empty())
      std::cout << "compatibility.runtime=" << installation.compatibilityRuntime << '\n';
    if (!installation.compatibilityRuntimePath.empty())
      std::cout << "compatibility.runtime_path=" << installation.compatibilityRuntimePath << '\n';
    if (!installation.compatibilityPrefix.empty())
      std::cout << "compatibility.prefix=" << installation.compatibilityPrefix << '\n';
    if (!installation.reason.empty())
      std::cout << "install.reason=" << installation.reason << '\n';
    std::cout << "legacy1161.pe32_i386=" << (installation.found ? "true" : "false") << '\n';
    std::cout << "legacy1161.launchable=" << (launchable(installation) ? "true" : "false") << '\n';
  }

  void printHelp()
  {
    std::cout
      << "usage: starcraft-runtime-legacy1161-setup [options]\n"
      << "  --dir <path>             directory containing StarCraft.exe/Brood War.exe\n"
      << "  --executable <path>      explicit Win32 StarCraft.exe/Brood War.exe\n"
      << "  --wine <path>            Wine executable for macOS/Linux hosts\n"
      << "  --wine-prefix <path>     Wine prefix to use when launching 1.16.1\n"
      << "  --write-env <path>       write shell exports for this installation\n"
      << "  --write-manifest <path>  write a non-production bootstrap manifest\n"
      << "  --require-launchable     fail unless the selected runtime can be launched\n"
      << "  --help                   show this help\n";
  }
}

int main(int argc, char** argv)
{
  RuntimeEnvironment environment = RuntimeEnvironment::detectHost();
  environment.product = Product::StarCraftBroodWar1161;
  environment.version = "1.16.1";

  std::string writeEnvPath;
  std::string writeManifestPath;
  bool requireLaunchable = false;

  for (int i = 1; i < argc; ++i)
  {
    const std::string arg = argv[i];
    if (arg == "--dir")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--dir requires a path\n";
        return 64;
      }
      setEnvValue("STARCRAFT_API_BW1161_DIR", argv[++i]);
    }
    else if (arg == "--executable")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--executable requires a path\n";
        return 64;
      }
      environment.executablePath = argv[++i];
    }
    else if (arg == "--wine")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--wine requires a path\n";
        return 64;
      }
      setEnvValue("STARCRAFT_API_WINE", argv[++i]);
    }
    else if (arg == "--wine-prefix")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--wine-prefix requires a path\n";
        return 64;
      }
      setEnvValue("STARCRAFT_API_WINEPREFIX", argv[++i]);
    }
    else if (arg == "--write-env")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--write-env requires a path\n";
        return 64;
      }
      writeEnvPath = argv[++i];
    }
    else if (arg == "--write-manifest")
    {
      if (i + 1 >= argc)
      {
        std::cerr << "--write-manifest requires a path\n";
        return 64;
      }
      writeManifestPath = argv[++i];
    }
    else if (arg == "--require-launchable")
    {
      requireLaunchable = true;
    }
    else if (arg == "--help" || arg == "-h")
    {
      printHelp();
      return 0;
    }
    else
    {
      std::cerr << "unknown argument: " << arg << '\n';
      return 64;
    }
  }

  RuntimeInstallation installation = detectStarCraftInstallation(environment);
  printInstallation(installation);

  std::string error;
  if (!writeEnvPath.empty())
  {
    if (!installation.found)
    {
      std::cerr << "cannot write env file before a valid 1.16.1 executable is selected\n";
      return 2;
    }
    if (!writeEnvFile(installation, writeEnvPath, error))
    {
      std::cerr << error << '\n';
      return 1;
    }
    std::cout << "env.path=" << writeEnvPath << '\n';
  }

  if (!writeManifestPath.empty())
  {
    if (!installation.found)
    {
      std::cerr << "cannot write manifest before a valid 1.16.1 executable is selected\n";
      return 2;
    }
    if (!writeRuntimeBootstrapManifest(installation, writeManifestPath, error))
    {
      std::cerr << error << '\n';
      return 1;
    }
    std::cout << "manifest.path=" << writeManifestPath << '\n';
  }

  if (requireLaunchable && !launchable(installation))
    return 2;
  return installation.found ? 0 : 2;
}
